vim.g.mapleader = " "
local keymap = vim.keymap

keymap.set("n", "<leader>h", ":nohl<CR>")
keymap.set("n", "x", '"_x')
keymap.set("n", "<leader>+", "<C-a>")
keymap.set("n", "<leader>-", "<C-x>")
keymap.set("n", "<leader>sv", "<C-w>v")
keymap.set("n", "<leader>sh", "<C-w>s")
keymap.set("n", "<leader>se", "<C-w>=")
keymap.set("n", "<leader>sx", ":close<CR>")
keymap.set("n", "<leader>sx", ":bd<CR>")
keymap.set("n", "<C-u>", "<C-u>zz")
keymap.set("n", "<C-d>", "<C-d>zz")
keymap.set("n", "j", "<Down>")
keymap.set("n", "k", "<Up>")
keymap.set("n", "h", "<Left>")
keymap.set("n", "l", "<Right>")
keymap.set("n", "<leader>F", "<cmd>lua vim.lsp.buf.format()<CR>")
keymap.set("n", "<CR>", "ciw")
keymap.set("n", "<leader>lg", "<cmd>LazyGit<CR>")
keymap.set("n", "<leader>ln", "<cmd>set nu!<CR>")
keymap.set("n", "<leader>e", "<cmd>Explore<CR>")
