require('custom.ts-fix')
require('custom.options')
require('custom.lazy')
require('custom.extras')
require('custom.formatting')
require('custom.keymaps')
require('custom.lsp')
require('custom.colours')
