vim.keymap.set("n", "j", "<Down>")
vim.keymap.set("n", "k", "<Up>")
vim.keymap.set("n", "h", "<Left>")
vim.keymap.set("n", "j", "<Right>")
vim.keymap.set("n", "<leader>e", "<cmd>Explore<CR>")
vim.keymap.set("n", "<Esc>", "<cmd>nohl<CR>")
vim.keymap.set("n", "m", "q")
vim.keymap.set("n", "q", "")
