require('plugins.catppuccin')
require('plugins.cmp')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.telescope')
-- require('plugins.lualine')
require('plugins.leap')
require('plugins.nvim-autopairs')
require('plugins.neo-tree')
-- require('plugins.gitsigns')
require('plugins.window-picker')
require('plugins.zen-mode')
require('plugins.indentblankline')
