-- require('plugins.catppuccin')
require('plugins.rose-pine')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.lualine')
require('plugins.leap')
require('plugins.nvim-autopairs')
require('plugins.neo-tree')
require('plugins.gitsigns')
require('plugins.indent-blankline')
require('plugins.window-picker')
require('plugins.zen-mode')
