require('plugins.cmp')
-- require('plugins.gitsigns')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.leap')
require('plugins.nvim-autopairs')
-- require('plugins.window-picker')
-- require('plugins.zen-mode')
require('plugins.telescope')
require('plugins.neo-tree')
